### ISSUE TITLE
 Relay Resource acting as reverse HTTP proxy

### ISSUE THREAD

**Issue by philsbln** [tireddy2/Reverse-HTTP-Transport#18]
To retrofit reverse-http in existing landscapes, it might be desirable not to require the client to be aware of reverse-http.
Instead, the client may use the relay-resource or another reverse http proxy that routes the request to the target resource.

We should consider this use case and add operational consideration.

**Comment by bemasc** [comment]
I think this is the main use case anticipated by the draft currently.  We can add text to emphasize that not modification to the "real client" is involved.

**Comment by bemasc** [comment]
I proposed some text about this at #19.  Does that address your concern?
